"""Remembered lookups: the cache and the archive

Revision ID: 9d38e68ee9d4
Revises: b17fa011c226
Create Date: 2026-09-19 16:11:09.567178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Our custom column types (MoneyAmount, UtcDateTime) are rendered by
# autogenerate as `app.db.types.X()`, but Alembic does not add the import that
# makes that name resolve. Without this line every generated migration fails
# with NameError on first run. Imported unconditionally because a migration
# that does not use it costs nothing.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '9d38e68ee9d4'
down_revision: Union[str, Sequence[str], None] = 'b17fa011c226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_lookups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('observed_at', app.db.types.UtcDateTime(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('flights', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'flight_number', 'flight_date', name='uq_flight_lookups_question')
    )
    with op.batch_alter_table('flight_lookups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_lookups_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index('ix_flight_lookups_question', ['flight_number', 'flight_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_lookups', schema=None) as batch_op:
        batch_op.drop_index('ix_flight_lookups_question')
        batch_op.drop_index(batch_op.f('ix_flight_lookups_observed_at'))

    op.drop_table('flight_lookups')
    # ### end Alembic commands ###
