"""Claims, passengers, expenses and documents.

What happens after a check says yes: who was on the booking, what the
disruption cost them out of pocket, and the files that prove it.

Four tables rather than more columns on eligibility_checks, because one check
becomes one claim covering several passengers with many receipts.

Unlike the first migration, this one was autogenerated against a database
already at head -- which is the case Alembic exists for, and the case
create_all() cannot handle at all.


Revision ID: f7739d9010e8
Revises: 4cfc08cbc8f0
Create Date: 2026-09-17 11:35:56.586461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Our custom column types (MoneyAmount, UtcDateTime) are rendered by
# autogenerate as `app.db.types.X()`, but Alembic does not add the import that
# makes that name resolve. Without this line every generated migration fails
# with NameError on first run. Imported unconditionally because a migration
# that does not use it costs nothing.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'f7739d9010e8'
down_revision: Union[str, Sequence[str], None] = '4cfc08cbc8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('check_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('airline_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_notice_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(), nullable=False),
    sa.Column('submitted_at', app.db.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['eligibility_checks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_check_id'), ['check_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_claims_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_claims_queue', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', app.db.types.MoneyAmount(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('incurred_on', sa.Date(), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_claim_id'), ['claim_id'], unique=False)

    op.create_table('passengers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('national_id', sa.String(length=40), nullable=True),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passengers_claim_id'), ['claim_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('expense_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_expense_id'), ['expense_id'], unique=False)



def downgrade() -> None:
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_expense_id'))
        batch_op.drop_index(batch_op.f('ix_documents_claim_id'))

    op.drop_table('documents')
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passengers_claim_id'))

    op.drop_table('passengers')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_claim_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index(batch_op.f('ix_claims_reference'))
        batch_op.drop_index('ix_claims_queue')
        batch_op.drop_index(batch_op.f('ix_claims_created_at'))
        batch_op.drop_index(batch_op.f('ix_claims_contact_email'))
        batch_op.drop_index(batch_op.f('ix_claims_check_id'))

    op.drop_table('claims')
