/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eligibility/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether a flight is owed compensation
         * @description Look up a flight and decide whether the passenger is owed anything.
         *
         *     Always returns 200 for a well-formed request, with the outcome in `status`.
         *     That is a deliberate choice: "no such flight" is not an HTTP error -- the
         *     endpoint worked, the lookup happened, and a record of it was stored. A 404
         *     here would tell a client the endpoint does not exist, and many HTTP
         *     libraries would discard the body that explains what actually went wrong.
         *
         *     A malformed request is a different matter and returns 422.
         */
        post: operations["check_eligibility_api_v1_eligibility_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eligibility/checks/{check_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a previous check
         * @description Read back a stored check.
         *
         *     Rebuilt from the stored snapshot rather than by asking the provider again:
         *     the answer must be the one the customer was actually given, not a fresh
         *     lookup that might now say something different.
         */
        get: operations["read_check_api_v1_eligibility_checks__check_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a claim from an eligibility check
         * @description Create a claim, with its passengers and expenses in one call.
         *
         *     One request rather than several, because a claim assembled over four round
         *     trips can fail on the third and leave a half-built record that nobody can
         *     finish and nobody will ever chase.
         */
        post: operations["create_claim_api_v1_claims_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/by-reference/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look a claim up the way a customer quotes it
         * @description Case- and space-insensitive, because it gets typed off a screenshot.
         */
        get: operations["read_claim_by_reference_api_v1_claims_by_reference__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a claim */
        get: operations["read_claim_api_v1_claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a booking confirmation or a receipt
         * @description Store one file against a claim.
         *
         *     The bytes go to storage, which decides the path; the database records where
         *     it went and what the customer called it. The original filename is never used
         *     to build a path -- see app/storage/files.py.
         */
        post: operations["upload_document_api_v1_claims__claim_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a finished claim */
        post: operations["submit_claim_api_v1_claims__claim_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts for the dashboard */
        get: operations["summary_api_v1_admin_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse eligibility checks
         * @description Newest first.
         *
         *     `verdict=NEEDS_REVIEW` is the query this endpoint exists for: the queue of
         *     everything the system could not decide, which must be worked by a person
         *     rather than quietly becoming a no.
         */
        get: operations["list_checks_api_v1_admin_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/checks/{check_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open one check */
        get: operations["read_check_api_v1_admin_checks__check_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse claims */
        get: operations["list_claims_api_v1_admin_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_claims__claim_id__documents_post */
        Body_upload_document_api_v1_claims__claim_id__documents_post: {
            /**
             * File
             * @description PDF or photo, up to 10 MB.
             */
            file: string;
            /** @default RECEIPT */
            kind: components["schemas"]["DocumentKind"];
            /** Expense Id */
            expense_id?: string | null;
        };
        /**
         * CheckDetail
         * @description One check, opened.
         *
         *     Carries the full evidence: the facts the verdict was computed from, every
         *     regulation's reasoning, and the untouched provider payload. That last one
         *     is what lets a disputed verdict be re-explained months later.
         */
        CheckDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Status */
            status: string;
            /** Verdict */
            verdict: string | null;
            /** Message */
            message: string | null;
            /** Best Regulation */
            best_regulation: string | null;
            /** Best Amount */
            best_amount: string | null;
            /** Best Currency */
            best_currency: string | null;
            /** Provider */
            provider: string;
            /** Has Claim */
            has_claim: boolean;
            /** Flight Snapshot */
            flight_snapshot: {
                [key: string]: unknown;
            } | null;
            /** Result Detail */
            result_detail: {
                [key: string]: unknown;
            } | null;
            /** Provider Payload */
            provider_payload: {
                [key: string]: unknown;
            } | null;
            /**
             * Others On This Flight
             * @description Everyone else who checked this flight. They usually belong in one claim: cheaper to run and far stronger against the airline than the same facts argued five times.
             */
            others_on_this_flight?: components["schemas"]["CheckRow"][];
        };
        /**
         * CheckRow
         * @description One check, as a row in the operator's list.
         */
        CheckRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Status */
            status: string;
            /** Verdict */
            verdict: string | null;
            /** Message */
            message: string | null;
            /** Best Regulation */
            best_regulation: string | null;
            /** Best Amount */
            best_amount: string | null;
            /** Best Currency */
            best_currency: string | null;
            /** Provider */
            provider: string;
            /** Has Claim */
            has_claim: boolean;
        };
        /** ClaimCreate */
        ClaimCreate: {
            /**
             * Check Id
             * Format: uuid
             * @description From the eligibility check.
             */
            check_id: string;
            /** Contact Name */
            contact_name: string;
            /**
             * Contact Email
             * Format: email
             */
            contact_email: string;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Booking Reference */
            booking_reference?: string | null;
            /**
             * Airline Reason
             * @description What reason the airline gave, in the customer's own words.
             */
            airline_reason?: string | null;
            /**
             * Cancellation Notice Days
             * @description For a cancellation: how many days' notice they were given.
             */
            cancellation_notice_days?: number | null;
            /** Passengers */
            passengers?: components["schemas"]["PassengerIn"][];
            /** Expenses */
            expenses?: components["schemas"]["ExpenseIn"][];
            /** Notes */
            notes?: string | null;
        };
        /** ClaimOut */
        ClaimOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Reference
             * @description Quote this. It is what a customer reads out on the phone.
             * @example FS-2026-K7M9QX
             */
            reference: string;
            status: components["schemas"]["ClaimStatus"];
            /**
             * Check Id
             * Format: uuid
             */
            check_id: string;
            /** Contact Name */
            contact_name: string;
            /** Contact Email */
            contact_email: string;
            /** Contact Phone */
            contact_phone: string | null;
            /** Booking Reference */
            booking_reference: string | null;
            /** Airline Reason */
            airline_reason: string | null;
            /** Cancellation Notice Days */
            cancellation_notice_days: number | null;
            /** Notes */
            notes: string | null;
            /** Passengers */
            passengers: components["schemas"]["PassengerOut"][];
            /** Expenses */
            expenses: components["schemas"]["ExpenseOut"][];
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
            /**
             * Expense Totals
             * @description Total expenses per currency, as exact decimal strings.
             * @example {
             *       "EUR": "226.20",
             *       "ILS": "240.50"
             *     }
             */
            expense_totals: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Submitted At */
            submitted_at: string | null;
        };
        /** ClaimRow */
        ClaimRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Status */
            status: string;
            /** Contact Name */
            contact_name: string;
            /** Contact Email */
            contact_email: string;
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Verdict */
            verdict: string | null;
            /** Best Amount */
            best_amount: string | null;
            /** Best Currency */
            best_currency: string | null;
            /** Passenger Count */
            passenger_count: number;
            /** Expense Count */
            expense_count: number;
            /** Document Count */
            document_count: number;
            /** Expense Totals */
            expense_totals: {
                [key: string]: string;
            };
        };
        /**
         * ClaimStatus
         * @description Where a claim is in its life.
         *
         *     Stored as a string rather than a database enum: this list will grow, and on
         *     PostgreSQL adding a value to an enum type is a migration with a table lock.
         * @enum {string}
         */
        ClaimStatus: "DRAFT" | "SUBMITTED" | "IN_REVIEW" | "SENT_TO_AIRLINE" | "AWAITING_AIRLINE" | "SETTLED" | "REJECTED" | "WITHDRAWN";
        /**
         * DocumentKind
         * @enum {string}
         */
        DocumentKind: "BOOKING" | "BOARDING_PASS" | "RECEIPT" | "IDENTIFICATION" | "CORRESPONDENCE" | "OTHER";
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Expense Id */
            expense_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            document: components["schemas"]["DocumentOut"];
            /** Claim Reference */
            claim_reference: string;
        };
        /**
         * EligibilityRequest
         * @description What the customer submits.
         */
        EligibilityRequest: {
            /**
             * Flight Number
             * @example BA165
             * @example LY324
             */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             * @description The day the flight DEPARTED, in the departure airport's local date.
             * @example 2026-08-14
             */
            flight_date: string;
            /** Contact Name */
            contact_name?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Option Key */
            option_key?: string | null;
        };
        /**
         * EligibilityResponse
         * @description The complete answer.
         * @example {
         *       "best_award": {
         *         "amount": "520.00",
         *         "currency": "GBP",
         *         "formatted": "£520.00"
         *       },
         *       "best_regulation": "UK261",
         *       "check_id": "9e3eca9b-6f28-4370-a5a0-6fa224474f62",
         *       "provider": "fake",
         *       "status": "DECIDED",
         *       "verdict": "ELIGIBLE"
         *     }
         */
        EligibilityResponse: {
            /**
             * Check Id
             * Format: uuid
             * @description Quote this when starting a claim.
             */
            check_id: string;
            /**
             * Status
             * @description DECIDED | NOT_FOUND | AMBIGUOUS | UNRESOLVED
             * @example DECIDED
             */
            status: string;
            /**
             * Verdict
             * @description ELIGIBLE | NOT_ELIGIBLE | NEEDS_REVIEW. Null for NOT_FOUND and AMBIGUOUS, which are questions rather than answers. NEEDS_REVIEW is never a polite no -- it means we could not decide.
             */
            verdict?: string | null;
            /** Message */
            message?: string | null;
            best_award?: components["schemas"]["MoneyOut"] | null;
            /** Best Regulation */
            best_regulation?: string | null;
            flight?: components["schemas"]["FlightOut"] | null;
            /**
             * Outcomes
             * @default []
             */
            outcomes: components["schemas"]["OutcomeOut"][];
            /**
             * Options
             * @default []
             */
            options: components["schemas"]["FlightOptionOut"][];
            /** Caveat */
            caveat?: string | null;
            /** Provider */
            provider: string;
        };
        /**
         * ExpenseCategory
         * @description What the money was spent on.
         *
         *     A fixed list rather than free text, because the whole point of collecting
         *     expenses is to total them and to argue they were reasonable -- neither of
         *     which works if one person writes "taxi" and the next writes "Uber home".
         * @enum {string}
         */
        ExpenseCategory: "MEAL" | "DRINK" | "HOTEL" | "TRANSPORT" | "COMMUNICATION" | "REBOOKING" | "OTHER";
        /** ExpenseIn */
        ExpenseIn: {
            category: components["schemas"]["ExpenseCategory"];
            /**
             * Amount
             * @example 180.00
             */
            amount: string;
            /**
             * Currency
             * @example EUR
             */
            currency: string;
            /** Description */
            description?: string | null;
            /** Incurred On */
            incurred_on?: string | null;
        };
        /** ExpenseOut */
        ExpenseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Category */
            category: string;
            /** Description */
            description: string | null;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Formatted */
            formatted: string;
            /** Incurred On */
            incurred_on: string | null;
            /** Document Count */
            document_count: number;
        };
        /**
         * FlightOptionOut
         * @description One of several flights sharing a number on a date.
         */
        FlightOptionOut: {
            /** Key */
            key: string;
            /** Route */
            route: string;
            /**
             * Label
             * @example DUB → STN, departing 16:00 UTC
             */
            label: string;
            /** Scheduled Departure */
            scheduled_departure: string | null;
        };
        /**
         * FlightOut
         * @description The flight as we understood it. Shown back so the customer can confirm
         *     we looked up the right one before building a claim on it.
         */
        FlightOut: {
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Airline */
            airline: string;
            /**
             * Route
             * @example TLV → LHR
             */
            route: string;
            /** Origin */
            origin: string;
            /** Origin Country */
            origin_country: string;
            /** Destination */
            destination: string;
            /** Destination Country */
            destination_country: string;
            /** Distance Km */
            distance_km: number;
            /** Status */
            status: string;
            /**
             * Scheduled Departure
             * Format: date-time
             */
            scheduled_departure: string;
            /**
             * Scheduled Arrival
             * Format: date-time
             */
            scheduled_arrival: string;
            /** Actual Departure */
            actual_departure: string | null;
            /** Actual Arrival */
            actual_arrival: string | null;
            /** Departure Delay Hours */
            departure_delay_hours: number | null;
            /** Arrival Delay Hours */
            arrival_delay_hours: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /**
         * MoneyOut
         * @description An amount, three ways.
         *
         *     `amount` is an exact decimal string, never a JSON number: JSON numbers are
         *     IEEE doubles in most parsers, and a payout that arrives in the browser as
         *     519.99999999 is the same bug Money exists to prevent, one layer further out.
         */
        MoneyOut: {
            /**
             * Amount
             * @example 520.00
             */
            amount: string;
            /**
             * Currency
             * @example GBP
             */
            currency: string;
            /**
             * Formatted
             * @example £520.00
             */
            formatted: string;
        };
        /**
         * OutcomeOut
         * @description One regulation's answer.
         *
         *     All three are always returned. An unexplained "no" destroys trust, and a
         *     customer who can see that two laws did not cover them and the third had a
         *     higher threshold understands the answer instead of doubting it.
         */
        OutcomeOut: {
            /**
             * Regulation
             * @example UK261
             */
            regulation: string;
            /**
             * Verdict
             * @example ELIGIBLE
             */
            verdict: string;
            /**
             * Applies
             * @description Whether this law covered the flight at all, whatever it concluded.
             */
            applies: boolean;
            /** Reason */
            reason: string;
            award?: components["schemas"]["MoneyOut"] | null;
        };
        /** Page[CheckRow] */
        Page_CheckRow_: {
            /** Items */
            items: components["schemas"]["CheckRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ClaimRow] */
        Page_ClaimRow_: {
            /** Items */
            items: components["schemas"]["ClaimRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PassengerIn */
        PassengerIn: {
            /** Full Name */
            full_name: string;
            /** National Id */
            national_id?: string | null;
            /**
             * Is Minor
             * @default false
             */
            is_minor: boolean;
        };
        /** PassengerOut */
        PassengerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** National Id */
            national_id: string | null;
            /** Is Minor */
            is_minor: boolean;
        };
        /** Readiness */
        Readiness: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
            /** Checks */
            checks: {
                [key: string]: string;
            };
        };
        /**
         * Summary
         * @description The numbers an operator looks at in the morning.
         */
        Summary: {
            /** Checks Total */
            checks_total: number;
            /** Checks By Verdict */
            checks_by_verdict: {
                [key: string]: number;
            };
            /** Checks By Status */
            checks_by_status: {
                [key: string]: number;
            };
            /** Claims Total */
            claims_total: number;
            /** Claims By Status */
            claims_by_status: {
                [key: string]: number;
            };
            /** Eligible Value By Currency */
            eligible_value_by_currency: {
                [key: string]: string;
            };
            /**
             * Needs Review
             * @description The size of the queue right now.
             */
            needs_review: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    check_eligibility_api_v1_eligibility_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EligibilityRequest"];
            };
        };
        responses: {
            /** @description The verdict, with every regulation's reasoning. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_check_api_v1_eligibility_checks__check_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_claim_api_v1_claims_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_claim_by_reference_api_v1_claims_by_reference__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_claim_api_v1_claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_claims__claim_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_claims__claim_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_claim_api_v1_claims__claim_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_admin_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checks_api_v1_admin_checks_get: {
        parameters: {
            query?: {
                /** @description ELIGIBLE | NOT_ELIGIBLE | NEEDS_REVIEW */
                verdict?: string | null;
                status?: string | null;
                flight_number?: string | null;
                flight_date?: string | null;
                contact_email?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CheckRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_check_api_v1_admin_checks__check_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_api_v1_admin_claims_get: {
        parameters: {
            query?: {
                status?: string | null;
                contact_email?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ClaimRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
