/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eligibility/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether a flight is owed compensation
         * @description Look up a flight and decide whether the passenger is owed anything.
         *
         *     Always returns 200 for a well-formed request, with the outcome in `status`.
         *     That is a deliberate choice: "no such flight" is not an HTTP error -- the
         *     endpoint worked, the lookup happened, and a record of it was stored. A 404
         *     here would tell a client the endpoint does not exist, and many HTTP
         *     libraries would discard the body that explains what actually went wrong.
         *
         *     A malformed request is a different matter and returns 422.
         */
        post: operations["check_eligibility_api_v1_eligibility_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eligibility/checks/{check_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a previous check
         * @description Read back a stored check, answered with TODAY's rules.
         *
         *     The flight data is the stored snapshot, never a fresh lookup: the facts
         *     of a flight in the past do not change, and re-asking a vendor would cost
         *     money to be told the same thing.
         *
         *     THE RULES, HOWEVER, ARE RE-RUN.
         *
         *     A verdict used to be written once and never revisited, so every rule
         *     improvement left everybody holding an older link seeing the older answer.
         *     Two hours apart on 27 September:
         *
         *         07:15  WZ4312  NEEDS_REVIEW
         *         11:19  A45024  LIKELY_ELIGIBLE  ILS1,530
         *
         *     Same flights, same data, a corrected rule in between -- and anyone who
         *     checked before lunch still had a page saying there was nothing here.
         *
         *     Nothing is written. A GET that mutates cannot be retried or cached
         *     safely, and two tabs on one claim would race. Recording the change is
         *     `app.tasks.reevaluate`, which reports what moved and can tell the people
         *     affected.
         */
        get: operations["read_check_api_v1_eligibility_checks__check_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a claim from an eligibility check
         * @description Create a claim, with its passengers and expenses in one call.
         *
         *     One request rather than several, because a claim assembled over four round
         *     trips can fail on the third and leave a half-built record that nobody can
         *     finish and nobody will ever chase.
         */
        post: operations["create_claim_api_v1_claims_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/by-reference/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look a claim up the way a customer quotes it
         * @description Case- and space-insensitive, because it gets typed off a screenshot.
         */
        get: operations["read_claim_by_reference_api_v1_claims_by_reference__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a claim */
        get: operations["read_claim_api_v1_claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a booking confirmation or a receipt
         * @description Store one file against a claim.
         *
         *     The bytes go to storage, which decides the path; the database records where
         *     it went and what the customer called it. The original filename is never used
         *     to build a path -- see app/storage/files.py.
         */
        post: operations["upload_document_api_v1_claims__claim_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a finished claim */
        post: operations["submit_claim_api_v1_claims__claim_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disruptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recently disrupted flights
         * @description Cancellations and long delays from the archive, worst first.
         *
         *     THE CACHE LIVES ON THE APP, NOT IN THIS MODULE.
         *
         *     A module-level global would be the shorter spelling and is wrong in a way
         *     that is invisible until it is not: it outlives the application object, so
         *     a second app in the same process -- a test, a worker reusing an
         *     interpreter, a script importing the routes -- inherits the first one's
         *     answers about a database it has never seen. It was written that way first,
         *     and the tests below caught it immediately by getting an empty board back
         *     from a database that had rows in it.
         *
         *     Hung off `app.state`, it is created with the app and dies with it.
         */
        get: operations["board_api_v1_disruptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What each law pays
         * @description The thresholds and amounts the engine applies, for the page that
         *     explains them.
         */
        get: operations["regulations_api_v1_regulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts for the dashboard */
        get: operations["summary_api_v1_admin_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse eligibility checks
         * @description Newest first.
         *
         *     `verdict=NEEDS_REVIEW` is the query this endpoint exists for: the queue of
         *     everything the system could not decide, which must be worked by a person
         *     rather than quietly becoming a no.
         */
        get: operations["list_checks_api_v1_admin_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/checks/{check_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open one check */
        get: operations["read_check_api_v1_admin_checks__check_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse claims */
        get: operations["list_claims_api_v1_admin_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone who has asked us about a flight */
        get: operations["list_customers_api_v1_admin_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/customers/{check_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything one customer submitted
         * @description Keyed on the CHECK, not the claim.
         *
         *     Every customer has a check; only some have a claim. Keying on the claim
         *     would mean the detail button works for the people who got through and
         *     404s for everybody who was refused -- who are the majority, and the ones
         *     worth revisiting when a rule changes.
         */
        get: operations["read_customer_api_v1_admin_customers__check_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download one uploaded file
         * @description The bytes of a receipt or a boarding pass.
         *
         *     THE KEY TRAVELS IN A HEADER, WHICH SHAPES HOW THIS IS USED. A browser
         *     cannot put a header on an `<a href>`, so the operator's screen fetches
         *     this with the key and hands the blob to the browser. That is deliberate:
         *     the alternative is a token in the URL, and URLs are written to server
         *     logs, proxy logs and browser history. A link to somebody's passport scan
         *     should not be sitting in three logs.
         *
         *     `Content-Disposition: attachment` and a fixed content type, because the
         *     bytes are customer-uploaded and rendering them inline in the operator's
         *     own origin would make an uploaded SVG or HTML file a script running on
         *     the admin page. The upload path already restricts types; this is the
         *     second lock on the same door.
         */
        get: operations["read_document_api_v1_admin_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BandOut
         * @description One distance band and what it pays.
         */
        BandOut: {
            /**
             * Up To Km
             * @description Upper bound of the band. Null for the top band, which has none.
             */
            up_to_km: number | null;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
        };
        /** BoardOut */
        BoardOut: {
            /** Updated At */
            updated_at: string;
            /** Days */
            days: number;
            /** Rows */
            rows: components["schemas"]["DisruptionOut"][];
        };
        /** Body_upload_document_api_v1_claims__claim_id__documents_post */
        Body_upload_document_api_v1_claims__claim_id__documents_post: {
            /**
             * File
             * @description PDF or photo, up to 10 MB.
             */
            file: string;
            /** @default RECEIPT */
            kind: components["schemas"]["DocumentKind"];
            /** Expense Id */
            expense_id?: string | null;
        };
        /**
         * CancellationNotice
         * @description How much warning the passenger got that the flight was cancelled.
         *
         *     Buckets, not a number of days, because a number cannot express the two
         *     answers that matter most. "I was never told" and "I cannot remember" are
         *     not quantities, and an integer column forces them into a null that reads
         *     identically to "not asked yet".
         *
         *     The boundary in both EC261 (Article 5(1)(c)) and the Israeli law is
         *     fourteen days, so the buckets are drawn around it: everything up to
         *     ONE_TO_TWO_WEEKS is plainly inside, OVER_TWO_WEEKS is plainly outside, and
         *     the last two are for a person to settle rather than for software to guess.
         * @enum {string}
         */
        CancellationNotice: "NEVER_TOLD" | "ON_THE_DAY" | "UNDER_A_WEEK" | "ONE_TO_TWO_WEEKS" | "OVER_TWO_WEEKS" | "CANNOT_REMEMBER";
        /**
         * CheckDetail
         * @description One check, opened.
         *
         *     Carries the full evidence: the facts the verdict was computed from, every
         *     regulation's reasoning, and the untouched provider payload. That last one
         *     is what lets a disputed verdict be re-explained months later.
         */
        CheckDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Status */
            status: string;
            /** Verdict */
            verdict: string | null;
            /** Message */
            message: string | null;
            /** Best Regulation */
            best_regulation: string | null;
            /** Best Amount */
            best_amount: string | null;
            /** Best Currency */
            best_currency: string | null;
            /** Provider */
            provider: string;
            /** Has Claim */
            has_claim: boolean;
            /** Flight Snapshot */
            flight_snapshot: {
                [key: string]: unknown;
            } | null;
            /** Result Detail */
            result_detail: {
                [key: string]: unknown;
            } | null;
            /** Provider Payload */
            provider_payload: {
                [key: string]: unknown;
            } | null;
            /**
             * Others On This Flight
             * @description Everyone else who checked this flight. They usually belong in one claim: cheaper to run and far stronger against the airline than the same facts argued five times.
             */
            others_on_this_flight?: components["schemas"]["CheckRow"][];
        };
        /**
         * CheckRow
         * @description One check, as a row in the operator's list.
         */
        CheckRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Status */
            status: string;
            /** Verdict */
            verdict: string | null;
            /** Message */
            message: string | null;
            /** Best Regulation */
            best_regulation: string | null;
            /** Best Amount */
            best_amount: string | null;
            /** Best Currency */
            best_currency: string | null;
            /** Provider */
            provider: string;
            /** Has Claim */
            has_claim: boolean;
        };
        /** ClaimCreate */
        ClaimCreate: {
            /**
             * Check Id
             * Format: uuid
             * @description From the eligibility check.
             */
            check_id: string;
            /** Contact Name */
            contact_name: string;
            /**
             * Contact Email
             * Format: email
             */
            contact_email: string;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Booking Reference */
            booking_reference?: string | null;
            /**
             * Airline Reason
             * @description What reason the airline gave, in the customer's own words.
             */
            airline_reason?: string | null;
            /**
             * @description For a cancellation: how much warning they were given. Buckets rather than a day count, because 'never told' and 'cannot remember' are not quantities and they are the answers that matter most.
             * @example NEVER_TOLD
             */
            cancellation_notice?: components["schemas"]["CancellationNotice"] | null;
            /** Passengers */
            passengers?: components["schemas"]["PassengerIn"][];
            /** Expenses */
            expenses?: components["schemas"]["ExpenseIn"][];
            /** Notes */
            notes?: string | null;
        };
        /** ClaimOut */
        ClaimOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Reference
             * @description Quote this. It is what a customer reads out on the phone.
             * @example FS-2026-K7M9QX
             */
            reference: string;
            status: components["schemas"]["ClaimStatus"];
            /**
             * Check Id
             * Format: uuid
             */
            check_id: string;
            /** Contact Name */
            contact_name: string;
            /** Contact Email */
            contact_email: string;
            /** Contact Phone */
            contact_phone: string | null;
            /** Booking Reference */
            booking_reference: string | null;
            /** Airline Reason */
            airline_reason: string | null;
            /** Cancellation Notice */
            cancellation_notice: string | null;
            /** Notes */
            notes: string | null;
            /** Passengers */
            passengers: components["schemas"]["PassengerOut"][];
            /** Expenses */
            expenses: components["schemas"]["ExpenseOut"][];
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
            /**
             * Expense Totals
             * @description Total expenses per currency, as exact decimal strings.
             * @example {
             *       "EUR": "226.20",
             *       "ILS": "240.50"
             *     }
             */
            expense_totals: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Submitted At */
            submitted_at: string | null;
        };
        /** ClaimRow */
        ClaimRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Status */
            status: string;
            /** Contact Name */
            contact_name: string;
            /** Contact Email */
            contact_email: string;
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Verdict */
            verdict: string | null;
            /** Best Amount */
            best_amount: string | null;
            /** Best Currency */
            best_currency: string | null;
            /** Passenger Count */
            passenger_count: number;
            /** Expense Count */
            expense_count: number;
            /** Document Count */
            document_count: number;
            /** Expense Totals */
            expense_totals: {
                [key: string]: string;
            };
        };
        /**
         * ClaimStatus
         * @description Where a claim is in its life.
         *
         *     Stored as a string rather than a database enum: this list will grow, and on
         *     PostgreSQL adding a value to an enum type is a migration with a table lock.
         * @enum {string}
         */
        ClaimStatus: "DRAFT" | "SUBMITTED" | "IN_REVIEW" | "SENT_TO_AIRLINE" | "AWAITING_AIRLINE" | "SETTLED" | "REJECTED" | "WITHDRAWN";
        /**
         * CustomerDetail
         * @description Everything the customer actually submitted, on one screen.
         *
         *     The point of the button. An operator about to write to an airline needs
         *     the passengers, the receipts and the two answers no database holds, and
         *     needs them without opening four tabs.
         */
        CustomerDetail: {
            /**
             * Check Id
             * Format: uuid
             */
            check_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Contact Phone */
            contact_phone: string | null;
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Verdict */
            verdict: string | null;
            /** Status */
            status: string;
            /** Best Amount */
            best_amount: string | null;
            /** Best Currency */
            best_currency: string | null;
            /** Claim Id */
            claim_id: string | null;
            /** Claim Reference */
            claim_reference: string | null;
            /** Claim Status */
            claim_status: string | null;
            /** Claim Submitted At */
            claim_submitted_at: string | null;
            /** Passenger Count */
            passenger_count: number;
            /** Document Count */
            document_count: number;
            /** Booking Reference */
            booking_reference: string | null;
            /** Airline Reason */
            airline_reason: string | null;
            /** Cancellation Notice */
            cancellation_notice: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Passengers
             * @default []
             */
            passengers: components["schemas"]["PassengerRow"][];
            /**
             * Expenses
             * @default []
             */
            expenses: components["schemas"]["ExpenseRow"][];
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["DocumentRow"][];
            /**
             * Expense Totals
             * @default {}
             */
            expense_totals: {
                [key: string]: string;
            };
            /** Result Detail */
            result_detail?: {
                [key: string]: unknown;
            } | null;
            /** Flight Snapshot */
            flight_snapshot?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CustomerRow
         * @description One person, as an operator needs to see them in a list.
         *
         *     Everything here answers "who is this and what do I do about them". The
         *     evidence -- snapshots, payloads, rule outcomes -- deliberately is not:
         *     it belongs on the detail screen, and putting it in the list would make
         *     a page that takes a second to load and cannot be scanned.
         */
        CustomerRow: {
            /**
             * Check Id
             * Format: uuid
             */
            check_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Contact Phone */
            contact_phone: string | null;
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Verdict */
            verdict: string | null;
            /** Status */
            status: string;
            /** Best Amount */
            best_amount: string | null;
            /** Best Currency */
            best_currency: string | null;
            /** Claim Id */
            claim_id: string | null;
            /** Claim Reference */
            claim_reference: string | null;
            /** Claim Status */
            claim_status: string | null;
            /** Claim Submitted At */
            claim_submitted_at: string | null;
            /** Passenger Count */
            passenger_count: number;
            /** Document Count */
            document_count: number;
        };
        /**
         * DisruptionOut
         * @description One row of the board.
         */
        DisruptionOut: {
            /** Flight Number */
            flight_number: string;
            /** Flight Date */
            flight_date: string;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Airline */
            airline: string;
            /**
             * Status
             * @description CANCELLED or DELAYED
             */
            status: string;
            /** Delay Hours */
            delay_hours: number | null;
            /** Verdict */
            verdict: string;
            /**
             * Amount
             * @description Formatted band amount, e.g. ₪1,530. Null when the data cannot support a figure -- which is most inbound flights, because the board knows only the Ben Gurion end.
             */
            amount: string | null;
        };
        /**
         * DocumentKind
         * @enum {string}
         */
        DocumentKind: "BOOKING" | "BOARDING_PASS" | "RECEIPT" | "IDENTIFICATION" | "CORRESPONDENCE" | "OTHER";
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Expense Id */
            expense_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DocumentRow
         * @description A file, described well enough to decide whether to open it.
         */
        DocumentRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expense Id */
            expense_id: string | null;
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            document: components["schemas"]["DocumentOut"];
            /** Claim Reference */
            claim_reference: string;
        };
        /**
         * EligibilityRequest
         * @description What the customer submits.
         */
        EligibilityRequest: {
            /**
             * Flight Number
             * @example BA165
             * @example LY324
             */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             * @description The day the flight DEPARTED, in the departure airport's local date.
             * @example 2026-08-14
             */
            flight_date: string;
            /** Contact Name */
            contact_name?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Option Key */
            option_key?: string | null;
        };
        /**
         * EligibilityResponse
         * @description The complete answer.
         * @example {
         *       "best_award": {
         *         "amount": "520.00",
         *         "currency": "GBP",
         *         "formatted": "£520.00"
         *       },
         *       "best_regulation": "UK261",
         *       "check_id": "9e3eca9b-6f28-4370-a5a0-6fa224474f62",
         *       "provider": "fake",
         *       "status": "DECIDED",
         *       "verdict": "ELIGIBLE"
         *     }
         */
        EligibilityResponse: {
            /**
             * Check Id
             * Format: uuid
             * @description Quote this when starting a claim.
             */
            check_id: string;
            /**
             * Status
             * @description DECIDED | NOT_FOUND | AMBIGUOUS | UNRESOLVED
             * @example DECIDED
             */
            status: string;
            /**
             * Verdict
             * @description ELIGIBLE | LIKELY_ELIGIBLE | NOT_ELIGIBLE | NEEDS_REVIEW. Null for NOT_FOUND and AMBIGUOUS, which are questions rather than answers. Neither NEEDS_REVIEW nor LIKELY_ELIGIBLE is a polite no: the first means we could not decide, the second means the law covers the flight and `best_award` is owed once the passenger answers `open_questions`.
             */
            verdict?: string | null;
            /** Message */
            message?: string | null;
            best_award?: components["schemas"]["MoneyOut"] | null;
            /** Best Regulation */
            best_regulation?: string | null;
            flight?: components["schemas"]["FlightOut"] | null;
            /**
             * Outcomes
             * @default []
             */
            outcomes: components["schemas"]["OutcomeOut"][];
            /**
             * Options
             * @default []
             */
            options: components["schemas"]["FlightOptionOut"][];
            /**
             * Open Questions
             * @description What to ask the passenger, each question once even when two laws wait on the same fact.
             * @default []
             * @example [
             *       "cancellation_notice"
             *     ]
             */
            open_questions: string[];
            /** Caveat */
            caveat?: string | null;
            /** Provider */
            provider: string;
        };
        /**
         * ExpenseCategory
         * @description What the money was spent on.
         *
         *     A fixed list rather than free text, because the whole point of collecting
         *     expenses is to total them and to argue they were reasonable -- neither of
         *     which works if one person writes "taxi" and the next writes "Uber home".
         * @enum {string}
         */
        ExpenseCategory: "MEAL" | "DRINK" | "HOTEL" | "TRANSPORT" | "COMMUNICATION" | "REBOOKING" | "OTHER";
        /** ExpenseIn */
        ExpenseIn: {
            category: components["schemas"]["ExpenseCategory"];
            /**
             * Amount
             * @example 180.00
             */
            amount: string;
            /**
             * Currency
             * @example EUR
             */
            currency: string;
            /** Description */
            description?: string | null;
            /** Incurred On */
            incurred_on?: string | null;
        };
        /** ExpenseOut */
        ExpenseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Category */
            category: string;
            /** Description */
            description: string | null;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Formatted */
            formatted: string;
            /** Incurred On */
            incurred_on: string | null;
            /** Document Count */
            document_count: number;
        };
        /** ExpenseRow */
        ExpenseRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Category */
            category: string;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Description */
            description: string | null;
        };
        /**
         * FlightOptionOut
         * @description One of several flights sharing a number on a date.
         */
        FlightOptionOut: {
            /** Key */
            key: string;
            /** Route */
            route: string;
            /**
             * Label
             * @example LCA → TLV, יוצאת ב-07:30
             */
            label: string;
            /** Scheduled Departure */
            scheduled_departure: string | null;
        };
        /**
         * FlightOut
         * @description The flight as we understood it. Shown back so the customer can confirm
         *     we looked up the right one before building a claim on it.
         */
        FlightOut: {
            /** Flight Number */
            flight_number: string;
            /**
             * Flight Date
             * Format: date
             */
            flight_date: string;
            /** Airline */
            airline: string;
            /**
             * Route
             * @example TLV → LHR
             */
            route: string;
            /** Origin */
            origin: string;
            /** Origin Country */
            origin_country: string;
            /** Destination */
            destination: string;
            /** Destination Country */
            destination_country: string;
            /** Distance Km */
            distance_km: number;
            /** Status */
            status: string;
            /** Scheduled Departure */
            scheduled_departure: string | null;
            /** Scheduled Arrival */
            scheduled_arrival: string | null;
            /** Actual Departure */
            actual_departure: string | null;
            /** Actual Arrival */
            actual_arrival: string | null;
            /** Departure Delay Hours */
            departure_delay_hours: number | null;
            /** Arrival Delay Hours */
            arrival_delay_hours: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /**
         * MoneyOut
         * @description An amount, three ways.
         *
         *     `amount` is an exact decimal string, never a JSON number: JSON numbers are
         *     IEEE doubles in most parsers, and a payout that arrives in the browser as
         *     519.99999999 is the same bug Money exists to prevent, one layer further out.
         */
        MoneyOut: {
            /**
             * Amount
             * @example 520.00
             */
            amount: string;
            /**
             * Currency
             * @example GBP
             */
            currency: string;
            /**
             * Formatted
             * @example £520.00
             */
            formatted: string;
        };
        /**
         * OutcomeOut
         * @description One regulation's answer.
         *
         *     All three are always returned. An unexplained "no" destroys trust, and a
         *     customer who can see that two laws did not cover them and the third had a
         *     higher threshold understands the answer instead of doubting it.
         */
        OutcomeOut: {
            /**
             * Regulation
             * @example UK261
             */
            regulation: string;
            /**
             * Verdict
             * @example ELIGIBLE
             */
            verdict: string;
            /**
             * Applies
             * @description Whether this law covered the flight at all, whatever it concluded.
             */
            applies: boolean;
            /** Reason */
            reason: string;
            award?: components["schemas"]["MoneyOut"] | null;
            /**
             * Open Question
             * @description Set on LIKELY_ELIGIBLE: the one fact the passenger has to supply before this becomes a definite answer.
             * @example cancellation_notice
             */
            open_question?: string | null;
        };
        /** Page[CheckRow] */
        Page_CheckRow_: {
            /** Items */
            items: components["schemas"]["CheckRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ClaimRow] */
        Page_ClaimRow_: {
            /** Items */
            items: components["schemas"]["ClaimRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[CustomerRow] */
        Page_CustomerRow_: {
            /** Items */
            items: components["schemas"]["CustomerRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PassengerIn */
        PassengerIn: {
            /** Full Name */
            full_name: string;
            /** National Id */
            national_id?: string | null;
            /**
             * Is Minor
             * @default false
             */
            is_minor: boolean;
        };
        /** PassengerOut */
        PassengerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** National Id */
            national_id: string | null;
            /** Is Minor */
            is_minor: boolean;
        };
        /** PassengerRow */
        PassengerRow: {
            /** Full Name */
            full_name: string;
            /** National Id */
            national_id: string | null;
            /** Is Minor */
            is_minor: boolean;
        };
        /** Readiness */
        Readiness: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
            /** Checks */
            checks: {
                [key: string]: string;
            };
        };
        /** RegulationOut */
        RegulationOut: {
            /** Key */
            key: string;
            /** Threshold Hours */
            threshold_hours: number;
            /**
             * Measured At
             * @description departure or arrival
             */
            measured_at: string;
            /** Bands */
            bands: components["schemas"]["BandOut"][];
        };
        /** RegulationsOut */
        RegulationsOut: {
            /** Regulations */
            regulations: components["schemas"]["RegulationOut"][];
        };
        /**
         * Summary
         * @description The numbers an operator looks at in the morning.
         */
        Summary: {
            /** Checks Total */
            checks_total: number;
            /** Checks By Verdict */
            checks_by_verdict: {
                [key: string]: number;
            };
            /** Checks By Status */
            checks_by_status: {
                [key: string]: number;
            };
            /** Claims Total */
            claims_total: number;
            /** Claims By Status */
            claims_by_status: {
                [key: string]: number;
            };
            /** Eligible Value By Currency */
            eligible_value_by_currency: {
                [key: string]: string;
            };
            /**
             * Needs Review
             * @description The size of the queue right now.
             */
            needs_review: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    check_eligibility_api_v1_eligibility_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EligibilityRequest"];
            };
        };
        responses: {
            /** @description The verdict, with every regulation's reasoning. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_check_api_v1_eligibility_checks__check_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_claim_api_v1_claims_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_claim_by_reference_api_v1_claims_by_reference__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_claim_api_v1_claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_claims__claim_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_claims__claim_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_claim_api_v1_claims__claim_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_api_v1_disruptions_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regulations_api_v1_regulations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulationsOut"];
                };
            };
        };
    };
    summary_api_v1_admin_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checks_api_v1_admin_checks_get: {
        parameters: {
            query?: {
                /** @description ELIGIBLE | NOT_ELIGIBLE | NEEDS_REVIEW */
                verdict?: string | null;
                status?: string | null;
                flight_number?: string | null;
                flight_date?: string | null;
                contact_email?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CheckRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_check_api_v1_admin_checks__check_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_api_v1_admin_claims_get: {
        parameters: {
            query?: {
                status?: string | null;
                contact_email?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ClaimRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_v1_admin_customers_get: {
        parameters: {
            query?: {
                /** @description ELIGIBLE | LIKELY_ELIGIBLE | NOT_ELIGIBLE | NEEDS_REVIEW */
                verdict?: string | null;
                /** @description Name, email, flight number or claim reference */
                search?: string | null;
                /** @description Only those who filed, or only those who did not */
                has_claim?: boolean | null;
                /** @description Include checks with no name and no email -- people who typed a flight number and left. Off by default: there is nobody to contact, and thousands of them would bury the rest. */
                include_anonymous?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CustomerRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_customer_api_v1_admin_customers__check_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_document_api_v1_admin_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
